### PR TITLE
Add project name as container data for loading and updating assets

### PR DESCRIPTION
**Pull request by moonyuet**
## Changelog Description
This PR is to add the `context["project"]["name"]` as part of the container data for loading and updating assets

## Additional review information
Please test along with this PR https://github.com/ynput/ayon-core/pull/1005

## Testing notes:
1. Launch Max
2. Load assets across different library projects

### CODE REVIEW

**Review by iLLiCiTiT — APPROVED** [review]

**Comment by iLLiCiTiT** [comment]
Didn' test it @antirotor could you?

**Review by LiborBatek — COMMENTED** [review]
Im able to load from Library project but Im not getting ```project name``` anywhere but ordinary ```model``` and ```variant```....is that right?? I guess not.

here is example with library loaded ```crateBox``` ```model``` into my active workfile...


image

**Comment by antirotor** [comment]
Oh f*ck, sorry. I had to change the ayon-core branch because of the dependency package rebuild and forgot the switch it back again...

**Review by antirotor — APPROVED** [review]
it works now, not sure why - but thats good news, no? :)

**Review by LiborBatek — APPROVED** [review]
After clarification of whats expected I have re-run the tests and it works correctly for me too...

image

LGTM.

**Pull request merged**
